SELECT RESULT.PRODUCT_ID, RESULT.PRODUCT_NAME, RESULT.TOTAL_SALES
FROM (
    SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
    FROM FOOD_ORDER AS O INNER JOIN FOOD_PRODUCT AS P ON O.PRODUCT_ID = P.PRODUCT_ID
    WHERE YEAR(O.PRODUCE_DATE) = 2022
        AND MONTH(O.PRODUCE_DATE) = 5
    GROUP BY O.PRODUCT_ID
) AS RESULT
ORDER BY RESULT.TOTAL_SALES DESC, RESULT.PRODUCT_ID ASC;