SELECT RESULT.PRICE_GROUP, COUNT(RESULT.PRODUCT_ID) AS PRODUCTS
FROM (
    SELECT PRODUCT_ID, FLOOR(PRICE / 10000) * 10000 AS PRICE_GROUP
    FROM PRODUCT
) AS RESULT
GROUP BY RESULT.PRICE_GROUP
ORDER BY RESULT.PRICE_GROUP ASC;