SELECT RESULT.HOUR, COUNT(ANIMAL_ID) AS `COUNT`
FROM (
    SELECT ANIMAL_ID, HOUR(DATETIME) AS `HOUR`
    FROM ANIMAL_OUTS
) AS RESULT
WHERE RESULT.HOUR BETWEEN 9 AND 19
GROUP BY RESULT.HOUR
ORDER BY RESULT.HOUR ASC