-- 코드를 입력하세요
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I LEFT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
# 띄어쓰기 기준으로 첫번째 단어
WHERE SUBSTRING_INDEX(I.SEX_UPON_INTAKE, " ", 1) = "Intact"
    AND SUBSTRING_INDEX(O.SEX_UPON_OUTCOME, " ", 1) IN ("Spayed", "Neutered")
ORDER BY BINARY I.ANIMAL_ID ASC