SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d")
FROM REST_REVIEW AS R INNER JOIN MEMBER_PROFILE AS P ON R.MEMBER_ID = P.MEMBER_ID
INNER JOIN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
) AS M ON P.MEMBER_ID = M.MEMBER_ID
ORDER BY R.REVIEW_DATE ASC, BINARY R.REVIEW_TEXT ASC