SELECT R.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS R INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON R.CAR_ID = H.CAR_ID
WHERE R.CAR_TYPE = "세단"
    AND MONTH(START_DATE) = 10
GROUP BY R.CAR_ID
ORDER BY R.CAR_ID DESC;