SELECT P.CATEGORY, M.MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT AS P INNER JOIN (
    SELECT MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS M ON P.PRICE = M.MAX_PRICE
WHERE P.CATEGORY IN ("과자", "국", "김치", "식용유")
GROUP BY P.CATEGORY
ORDER BY M.MAX_PRICE DESC;