SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(H.CAR_ID) AS RECORDS
FROM (
    # 2022. 08 ~ 2022. 10 ID별 총 수량
    SELECT CAR_ID, COUNT(CAR_ID) AS TOTAL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022
        AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING TOTAL >= 5
) AS R INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON R.CAR_ID = H.CAR_ID
WHERE YEAR(H.START_DATE) = 2022
    AND MONTH(H.START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, CAR_ID DESC;