SELECT R.ITEM_ID, R.ITEM_NAME, R.RARITY
FROM ITEM_INFO AS I INNER JOIN ITEM_TREE AS T ON I.ITEM_ID = T.PARENT_ITEM_ID AND I.RARITY = "RARE"
    INNER JOIN ITEM_INFO AS R ON T.ITEM_ID = R.ITEM_ID
ORDER BY R.ITEM_ID DESC;