SELECT RESULT.CAR_ID, RESULT.CAR_TYPE, RESULT.FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE,
        FLOOR(C.DAILY_FEE * 30 * (1 - COALESCE(P.DISCOUNT_RATE, 0) / 100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C LEFT JOIN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
        HAVING MAX(END_DATE) < "2022-11-01"
    ) AS H ON C.CAR_ID = H.CAR_ID
    INNER JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE (CAR_TYPE = "세단" OR CAR_TYPE = "SUV")
            AND DURATION_TYPE = "30일 이상"
    ) AS P ON C.CAR_TYPE = P.CAR_TYPE
    WHERE H.CAR_ID IS NOT NULL
        AND (C.CAR_TYPE = "SUV" OR C.CAR_TYPE = "세단")
) AS RESULT
WHERE RESULT.FEE BETWEEN 500000 AND 1999999
ORDER BY RESULT.FEE DESC, RESULT.CAR_TYPE ASC, RESULT.CAR_ID DESC;