WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR +1
    FROM CTE
    WHERE HOUR < 23
)

SELECT C.HOUR, COUNT(O.ANIMAL_ID)
FROM CTE AS C LEFT JOIN ANIMAL_OUTS AS O ON C.HOUR = HOUR(O.DATETIME)
GROUP BY C.HOUR;