SELECT RESULT.FISH_COUNT, RESULT.FISH_NAME
FROM (
    SELECT COUNT(I.ID) AS FISH_COUNT, N.FISH_NAME
    FROM FISH_INFO AS I INNER JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY N.FISH_NAME
) AS RESULT
ORDER BY FISH_COUNT DESC;