SELECT M.YEAR, M.MAX - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E INNER JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS M ON YEAR(DIFFERENTIATION_DATE) = M.YEAR
ORDER BY M.YEAR ASC, YEAR_DEV ASC;