SELECT RESULT.PRODUCT_CODE, RESULT.SALES
FROM (
    SELECT P.PRODUCT_CODE, SUM(P.PRICE * S.SALES_AMOUNT) AS SALES
    FROM PRODUCT AS P INNER JOIN OFFLINE_SALE AS S ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY PRODUCT_CODE
) AS RESULT
ORDER BY RESULT.SALES DESC, BINARY RESULT.PRODUCT_CODE ASC;