SELECT S.ROUTE, CONCAT(ROUND(SUM(S.D_BETWEEN_DIST), 1), "km") AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(S.D_BETWEEN_DIST), 2), "km") AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE AS S
GROUP BY S.ROUTE
ORDER BY ROUND(SUM(S.D_BETWEEN_DIST), 1) DESC;