SELECT RESULT.USER_ID, RESULT.NICKNAME, RESULT.전체주소, RESULT.전화번호
FROM
(
    SELECT COUNT(BOARD_ID) AS CNT, U.USER_ID, U.NICKNAME,
        CONCAT(U.CITY, " ", U.STREET_ADDRESS1, " ", U.STREET_ADDRESS2) AS 전체주소,
        CONCAT(LEFT(TLNO, 3), "-", MID(TLNO, 4, 4), "-", RIGHT(TLNO, 4)) AS 전화번호
    FROM USED_GOODS_BOARD AS B LEFT JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
    GROUP BY U.USER_ID
) AS RESULT
WHERE RESULT.CNT >= 3
ORDER BY BINARY RESULT.USER_ID DESC;