SELECT RESULT.HISTORY_ID, RESULT.CAR_ID, RESULT.START_DATE, RESULT.END_DATE, CASE WHEN
    RESULT.RENT >= 30 THEN "장기 대여" ELSE "단기 대여"
END AS RENT_TYPE
FROM (
    SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, "%Y-%m-%d") AS START_DATE, DATE_FORMAT(END_DATE, "%Y-%m-%d") AS END_DATE, DATEDIFF(END_DATE, START_DATE) + 1 AS RENT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022
        AND MONTH(START_DATE) = 9
) AS RESULT
ORDER BY RESULT.HISTORY_ID DESC;