SELECT D.ID, D.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS D LEFT JOIN ECOLI_DATA AS P ON D.PARENT_ID = P.ID
WHERE D.PARENT_ID IS NOT NULL
    AND D.GENOTYPE & (P.GENOTYPE) = (P.GENOTYPE)
ORDER BY D.ID ASC;