SELECT RESULT.REST_ID, RESULT.REST_NAME, RESULT.FOOD_TYPE, RESULT.FAVORITES, RESULT.ADDRESS, RESULT.SCORE
FROM (
    SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
    FROM REST_INFO AS I INNER JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID
    WHERE LEFT(I.ADDRESS, 2) = "서울"
    GROUP BY I.REST_ID
) AS RESULT
ORDER BY RESULT.SCORE DESC, FAVORITES DESC;