SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID) / C.TOTAL, 1) AS PUCHASED_RATIO
FROM USER_INFO AS U INNER JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID AND YEAR(U.JOINED) = 2021
CROSS JOIN (SELECT COUNT(USER_ID) AS TOTAL FROM USER_INFO WHERE YEAR(JOINED) = 2021) AS C
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;