# 세대 구하기
WITH RECURSIVE CTE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D.ID, D.PARENT_ID, C.GENERATION + 1 AS GENERATION
	FROM ECOLI_DATA AS D INNER JOIN CTE AS C ON D.PARENT_ID = C.ID
)

SELECT COUNT(C.ID) AS COUNT, C.GENERATION
FROM CTE AS C LEFT JOIN (
    # 있는 자식을 먼저 찾음
    SELECT C.ID
    FROM ECOLI_DATA AS C INNER JOIN ECOLI_DATA AS P ON C.ID = P.PARENT_ID
    GROUP BY C.ID
) AS R ON C.ID = R.ID
# LEFT JOIN으로 연결하면 없는 자식이 NULL로 표현됨
WHERE R.ID IS NULL
# 세대로 묶어서 C.ID로 COUNT
GROUP BY C.GENERATION
ORDER BY C.GENERATION ASC;