SELECT B.BOARD_ID, B.WRITER_ID, B.TITLE, B.PRICE, CASE
    WHEN B.STATUS = "SALE" THEN "판매중"
    WHEN B.STATUS = "DONE" THEN "거래완료"
    ELSE "예약중"
END AS `STATUS`
FROM USED_GOODS_BOARD AS B
WHERE DATE_FORMAT(B.CREATED_DATE, "%Y-%m-%d") = "2022-10-05"
ORDER BY BINARY B.BOARD_ID DESC;