SELECT RESULT.CAR_ID, RESULT.AVERAGE_DURATION
FROM (
    SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
) AS RESULT
WHERE RESULT.AVERAGE_DURATION >= 7
ORDER BY RESULT.AVERAGE_DURATION DESC, RESULT.CAR_ID DESC;