SELECT RESULT.ID, CASE
    WHEN PERCENT <= 25 THEN "CRITICAL"
    WHEN PERCENT <= 50 THEN "HIGH"
    WHEN PERCENT <= 75 THEN "MEDIUM"
    ELSE "LOW"
END AS COLONY_NAME
FROM (
    SELECT ID, SIZE_OF_COLONY, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 AS PERCENT
    FROM ECOLI_DATA
) AS RESULT
ORDER BY ID ASC;