# 동일한 회원이 동일한 상품을 재구매한 데이터를 구하여, 재구매한 회원 ID와 재구매한 상품 ID를 출력
SELECT RESULT.USER_ID, RESULT.PRODUCT_ID
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(USER_ID) AS CNT
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
) AS RESULT
WHERE RESULT.CNT > 1
ORDER BY RESULT.USER_ID ASC, RESULT.PRODUCT_ID DESC;