SELECT RESULT.CODE AS `진료과 코드`, RESULT.CNT AS `5월예약건수`
FROM (
    SELECT MCDP_CD AS `CODE`, COUNT(PT_NO) AS `CNT`
    FROM APPOINTMENT 
    WHERE APNT_YMD between "2022-05-01" and "2022-05-31"
    GROUP BY MCDP_CD
) AS RESULT
ORDER BY RESULT.CNT, BINARY RESULT.CODE;