SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I INNER JOIN ITEM_TREE AS T ON I.ITEM_ID = T.ITEM_ID
    LEFT JOIN ITEM_TREE AS P ON T.ITEM_ID = P.PARENT_ITEM_ID
WHERE P.PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID DESC;