SELECT I.ID, N.FISH_NAME, L.LENGTH
FROM FISH_INFO AS I INNER JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
INNER JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
) AS L ON L.FISH_TYPE = I.FISH_TYPE AND L.LENGTH = I.LENGTH
ORDER BY I.ID ASC;