SELECT RESULT.USER_ID, RESULT.NICKNAME, RESULT.TOTAL_SALES
FROM (
    SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD AS B INNER JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
    WHERE B.STATUS = "DONE"
    GROUP BY U.USER_ID
) AS RESULT
WHERE RESULT.TOTAL_SALES >= 700000
ORDER BY RESULT.TOTAL_SALES ASC;