WITH RECURSIVE CTE AS (
	SELECT ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE,
        # NULL인 경우 1세대
        1 AS GENERATION
	FROM ECOLI_DATA
	WHERE PARENT_ID IS NULL

	UNION ALL

	SELECT D.ID, D.PARENT_ID, D.SIZE_OF_COLONY, D.DIFFERENTIATION_DATE, D.GENOTYPE,
        # 세대가 반복될수록 + 1
        C.GENERATION + 1 AS GENERATION
	FROM ECOLI_DATA AS D INNER JOIN CTE AS C ON D.PARENT_ID = C.ID
)

SELECT ID FROM CTE
WHERE GENERATION = 3
ORDER BY ID ASC;